### PR TITLE
Tiny

### PR DESCRIPTION
**Pull request by stsp**
switch to TINY model

### CODE REVIEW

**Comment by andrewbird** [comment]
FDPP travis only checks for build success, doesn't run the dosemu tests.

**Comment by stsp** [comment]
Looks like I managed!
But how to run the full test now?

**Comment by andrewbird** [comment]
Checkout the test branch I just made and push it to your own topic branch https://github.com/andrewbird/dosemu2/tree/do_full_tests_with_fdpp_branch. You should then be able push to it, or just press the retest button in Travis to retest your changes in 'tiny' branch of fdpp.

**Comment by andrewbird** [comment]
Actually, there's no point in doing **all** DOS tests to check FDPP, so you might want to remove the travis_test.sh changes I made.

**Pull request merged**
